modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "CC0-1.0"
issueTrackerURL = "https://github.com/bshuler/critical-orientation/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
description = '''${description}'''
authors = "TheCritic"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/critical-orientation"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"
