modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "CC0-1.0"
issueTrackerURL = "https://github.com/bshuler/critical-orientation/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''${mod_description}'''
authors = "TheCritic"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/critical-orientation"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"
