modLoader = "javafml"
loaderVersion = "[4,)"
license = "CC0-1.0"
issueTrackerURL = "https://github.com/bshuler/critical-orientation/issues"

[[mods]]
modId = "orientation"
version = "${version}"
displayName = "Critical Orientation"
description = '''
Snaps player direction to cardinal and intercardinal directions for precise ice boat placement.
'''
authors = "TheCritic"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/critical-orientation"

[[dependencies.orientation]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.orientation]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.22)"
ordering = "NONE"
side = "CLIENT"
